from typing import Protocol, List, Optional, Dict
from src.domain.book import Book


class BookRepositoryProtocol(Protocol):
    def get_all_books(self) -> List[Book]: ...

    def add_book(self, book: Book) -> str: ...

    def get_book_by_id(self, book_id: str) -> Optional[Book]: ...

    def update_book(self, book_id: str, data: Dict) -> Optional[Book]: ...

    def delete_book(self, book_id: str) -> bool: ...

    def find_book_by_name(self, query: str) -> List[Book]: ...

    def append_checkout_history(self, book_id: str, entry: Dict) -> None: ...
